import { create } from 'zustand';
import * as Crypto from 'expo-crypto';
import { CaseRecord, CaseSource, Subscription } from '@/types/domain';
import { deleteCase, eraseAll, getIdentifier, listCases, saveCase } from '@/services/repository';
import { LinkOnlyConnector, UscisConnector } from '@/services/connectors';
import { normalizeReceipt } from '@/services/validation';
import { inferMilestone } from '@/data/guidance';
import { sampleCases } from '@/data/sample';
import { createCloudCase } from '@/services/cloudCases';

interface AppState {cases:CaseRecord[];loaded:boolean;onboarded:boolean;subscription:Subscription;load:()=>Promise<void>;completeOnboarding:()=>void;addCase:(input:{source:CaseSource;identifier:string;nickname:string;applicant:string;formType:string})=>Promise<string>;refreshCase:(id:string)=>Promise<void>;updateCase:(id:string,patch:Partial<Pick<CaseRecord,'reminders'|'documentNotes'|'cloudId'|'migrationState'>>)=>Promise<void>;syncCases:()=>Promise<{synced:number;failed:number}>;removeCase:(id:string)=>Promise<void>;erase:()=>Promise<void>;seedDemo:()=>Promise<void>;}
const connectorFor=(s:CaseSource)=>s==='uscis'?new UscisConnector():new LinkOnlyConnector(s);
export const useAppStore=create<AppState>((set,get)=>({
  cases:[],loaded:false,onboarded:false,subscription:{tier:'free'},
  load:async()=>set({cases:await listCases(),loaded:true}),completeOnboarding:()=>set({onboarded:true}),
  addCase:async(input)=>{const connector=connectorFor(input.source);if(!connector.validateIdentifier(input.identifier))throw new Error(`Enter a valid ${input.source.toUpperCase()} identifier.`);if(get().cases.length>=5&&get().subscription.tier==='free')throw new Error('The free plan supports up to five cases.');const canonical=input.source==='uscis'?normalizeReceipt(input.identifier):input.identifier.trim();for(const c of get().cases){if(await getIdentifier(c.id)===canonical)throw new Error('This case is already being tracked.');}const id=Crypto.randomUUID();let status=input.source==='uscis'?'Case Was Received':'Official status link ready';let rawEvents:unknown[]=[];try{const fetched=await connector.fetchStatus(canonical);status=fetched.status;rawEvents=fetched.rawEvents;}catch(e){if(input.source==='uscis'&&process.env.EXPO_PUBLIC_API_BASE_URL)throw e;}const events=await connector.normalizeEvents(rawEvents,id);const now=new Date().toISOString();const record:CaseRecord={id,source:input.source,nickname:input.nickname||input.formType,applicant:input.applicant||'Me',formType:input.formType||input.source.toUpperCase(),status,milestone:inferMilestone(status),lastUpdatedAt:now,createdAt:now,terminal:false,events:events.length?events:[{id:`${id}-created`,caseId:id,status,description:status,occurredAt:now,milestone:inferMilestone(status),sourceHash:`${id}-created`}],snapshot:connector.getFreshness()};await saveCase(record,canonical);set({cases:[record,...get().cases]});return id;},
  refreshCase:async(id)=>{const current=get().cases.find(c=>c.id===id);if(!current)return;const identifier=await getIdentifier(id);if(!identifier)throw new Error('Secure case identifier is unavailable.');const connector=connectorFor(current.source);const fetched=await connector.fetchStatus(identifier,current);const incoming=await connector.normalizeEvents(fetched.rawEvents,id);const seen=new Set(current.events.map(e=>e.sourceHash));const merged=[...incoming.filter(e=>!seen.has(e.sourceHash)),...current.events].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));const updated={...current,status:fetched.status,formType:fetched.formType||current.formType,milestone:inferMilestone(fetched.status),terminal:fetched.terminal,events:merged,lastUpdatedAt:new Date().toISOString(),snapshot:connector.getFreshness()};await saveCase(updated);set({cases:get().cases.map(c=>c.id===id?updated:c)});},
  updateCase:async(id,patch)=>{const current=get().cases.find(c=>c.id===id);if(!current)return;const updated={...current,...patch,lastUpdatedAt:new Date().toISOString()};await saveCase(updated);set({cases:get().cases.map(c=>c.id===id?updated:c)});},
  syncCases:async()=>{let synced=0,failed=0;for(const current of get().cases.filter(c=>c.source==='uscis'&&!c.cloudId)){const identifier=await getIdentifier(current.id);if(!identifier){failed++;continue;}const pending={...current,migrationState:'pending' as const};await saveCase(pending);set({cases:get().cases.map(c=>c.id===current.id?pending:c)});try{const cloud=await createCloudCase(current,identifier);const complete={...pending,cloudId:cloud.id,migrationState:'synced' as const};await saveCase(complete);set({cases:get().cases.map(c=>c.id===current.id?complete:c)});synced++;}catch{const failedRecord={...pending,migrationState:'failed' as const};await saveCase(failedRecord);set({cases:get().cases.map(c=>c.id===current.id?failedRecord:c)});failed++;}}return{synced,failed};},
  removeCase:async id=>{await deleteCase(id);set({cases:get().cases.filter(c=>c.id!==id)});},erase:async()=>{await eraseAll();set({cases:[]});},seedDemo:async()=>{for(const c of sampleCases)await saveCase(c,'IOE0912345678');set({cases:sampleCases});}
}));
