import { Alert, Share, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, H1, H2, Pill, Screen } from '@/components/ui';
import { useAppStore } from '@/store/useAppStore';
import { registerForPush } from '@/services/notifications';
import { saveInstallation } from '@/services/cloudCases';
import { supported } from '@/i18n';
import { useTheme } from '@/theme';
export default function Settings(){const t=useTheme();const {cases,erase,syncCases}=useAppStore();return <Screen><H1>Settings</H1><Card><View style={s.row}><View style={s.grow}><H2>Account and sync</H2><Text style={[s.copy,{color:t.muted}]}>{cases.filter(c=>c.cloudId).length} of {cases.filter(c=>c.source==='uscis').length} USCIS cases encrypted in cloud sync.</Text></View><Pill>Private</Pill></View><Button title="Create or sign in to free account" onPress={()=>router.push('/account')}/><Button title="Sync cases now" secondary onPress={async()=>{try{const result=await syncCases();Alert.alert('Sync finished',`${result.synced} synced · ${result.failed} need attention. Local cases are kept when a cloud upload fails.`);}catch(e){Alert.alert('Sync unavailable',e instanceof Error?e.message:'Try again.');}}}/></Card><Card><H2>Notifications</H2><Text style={[s.copy,{color:t.muted}]}>Case alerts are kept separate from educational updates.</Text><Button title="Enable case alerts" secondary onPress={async()=>{try{const token=await registerForPush();await saveInstallation(token,Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC');Alert.alert('Alerts enabled','This signed-in device is registered for deduplicated server alerts.');}catch(e){Alert.alert('Could not enable alerts',e instanceof Error?e.message:'Open system settings to try again.');}}}/></Card><Card><H2>Language</H2><Text style={[s.copy,{color:t.muted}]}>{Object.values(supported).join(' · ')}</Text><Text style={[s.note,{color:t.muted}]}>The app follows the device language. Reviewed guidance content must be professionally translated before store release.</Text></Card><Card><H2>Your data</H2><Button title="Export case history" secondary onPress={()=>Share.share({title:'NextStep case export',message:JSON.stringify({exportedAt:new Date().toISOString(),cases:cases.map(({id,nickname,applicant,formType,status,milestone,lastUpdatedAt,events})=>({id,nickname,applicant,formType,status,milestone,lastUpdatedAt,events}))},null,2)})}/><Button title="Delete all local data" secondary onPress={()=>Alert.alert('Delete all local data?','This permanently removes case history and protected identifiers from this device.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:erase}])}/></Card><Card><H2>Privacy promise</H2><Text style={[s.copy,{color:t.ink}]}>No ads. No receipt numbers in analytics or logs. Identifiers are stored separately in protected device storage. You can export or erase your data at any time.</Text></Card><Text style={[s.note,{color:t.muted}]}>Independent educational software. Not affiliated with USCIS, the Department of State, EOIR, or any U.S. government entity. Not legal advice.</Text></Screen>}
const s=StyleSheet.create({row:{flexDirection:'row',gap:12,alignItems:'flex-start'},grow:{flex:1},copy:{fontSize:15,lineHeight:22},note:{fontSize:12,lineHeight:18,textAlign:'center'}});
